2022-02-26 15:40:06,642 - base_log.py[line:31] - ERROR: 执行用例1的时候报错:
2022-02-26 15:40:07,104 - base_log.py[line:31] - ERROR: 执行用例2的时候报错:
2022-02-26 15:40:12,576 - base_log.py[line:31] - ERROR: 执行用例11的时候报错:
