2022-02-26 15:11:06,681 - base_log.py[line:31] - ERROR: 执行用例2的时候报错:
2022-02-26 15:11:12,331 - base_log.py[line:31] - ERROR: 执行用例11的时候报错:
